[BB-6206] Implement a way to add "Edit" links based on block ids
open-craft/openedx-edit-links pull request #1
Opened 2022-06-24 10:49 UTC by tecoholic

### Description
The first feature functional PR to the edit_links Open edX extension.

* Adds a model with admin view to configure course specfiic repositories
  and the base_url to the edit interfaces of the source code hosting
  services that hold the course information.
* Implements the pipeline for
  `org.openedx.learning.xblock.render.started.v1` event, that can
  generate the "Edit this on <some-service>" links to the XBlocks based
  on the XBlock IDs

**JIRA:** https://tasks.opencraft.com/browse/BB-6206

**Dependencies:** 
- edx-platform - https://github.com/openedx/edx-platform/pull/30650
- openedx-filters - https://github.com/openedx/openedx-filters/pull/35

**Installation instructions:**

This assumes you are testing this on a devstack.

1. Checkout the [edx-platform PR](https://github.com/openedx/edx-platform/pull/30650) branch. Note: add the **open-craft** remote if you don't have it already.
    ```
    git checkout open-craft/tecoholic/BB-6206-edit-links-poc
    ```
2. Clone the edx-filters repository to the `src` folder and checkout to the [corresponding PR](https://github.com/openedx/openedx-filters/pull/35) branch 
    ```
    cd <your-devstack-location>/src
    git clone https://github.com/open-craft/openedx-filters.git
    # if you already have openedx repo checkout, add the open-craft remote and fetch the PR branch
    git checkout tecoholic/BB-6206-edit-links-poc
    ```
3. Clone the repository to your `src` directory in your devstack setup and checkout to the PR branch
    ```
    git clone https://github.com/open-craft/openedx-edit-links.git
    git checkout tecoholic/BB-6206-edit-links-poc
    ```
5. Drop into LMS shell and install the openedx-filters extension and the openedx-edit-links extension
    ```
    make lms-shell
    pip install -e /edx/src/openedx-filters
    pip install -e /edx/src/openedx-edit-links

    # run the DB migrations for the extension
    python manage.py lms migrate edit_links
    ```
6. Add the following configuration to `lms/envs/private.py` of `edx-platform`
    ```python
    from .common import INSTALLED_APPS
    
    INSTALLED_APPS += ["edit_links",]

    OPEN_EDX_FILTERS_CONFIG = {
            "org.openedx.learning.xblock.render.started.v1": {
                "fail_silently": False,
                "pipeline": [
                    "edit_links.pipeline.AddEditLink"
                ]
            }
        }
    ```
7. Restart the LMS `make lms-restart`

**Testing instructions:**

One the extension is installed and configured as above, we can test the extension using the MOOC FLOSS course content.

1. Download the `course` folder from https://gitlab.com/mooc-floss/mooc-floss/-/tree/master/course as a `.tar.gz` file. 
![poc-download-course](https://user-images.githubusercontent.com/383862/175516855-b6fafe27-9e57-4f98-855d-00af647fa0c3.png)
2. Create a new course in studio and go to **Tools** > **Import** and upload the `.tar.gz` file just downloaded.
3. If you face a "problem-builder" related error during the import, install the [Problem Builder XBlock](https://github.com/open-craft/problem-builder) in both studio and lms containers and then try the import process again.
    ```
    make lms-shell
    pip install xblock-problem-builder
    make studio-shell
    pip install xblock-problem-builder
    ```
4. Ensure the course is successfully imported and the units are loading in the LMS. Make a note of the course ID eg., `course-v1:FLOSS+OSS101+2022_T4`
5. Go to LMS Admin > Edit Links > EditLinkedCourses (http://localhost:18000/admin/edit_links/editlinkedcourse/) 
6. Click "Add Edit Linked Course" and add the following details and save.
    - Course ID: `the course id you noted`
    - Repository URL: `https://gitlab.com/mooc-floss/mooc-floss/`
    - Edit tool base url: `https://gitlab.com/-/ide/project/mooc-floss/mooc-floss/edit/master/-/course/html/`
7. Now re-open the course in LMS, each unit should have a **Edit in Gitlab** link on the top. 
![poc_edit_link](https://user-images.githubusercontent.com/383862/175518990-64db7dd9-36de-4cb1-a254-74ce2a797d24.png)
8. Clicking the link should take the user directly to the Gitlab IDE with the contents of the unit available as editable HTML.

**Reviewers:**
- [ ] @navinkarkera

cc: @antoviaque @pomegranited 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:**

The UI is slightly difference from the UI mockup discussed in https://gitlab.com/mooc-floss/mooc-floss/-/issues/112 - as in the edit link doesn't appear in the same line as the heading. This is because, the heading is rendered by the **Learning MFE** and the VerticalBlocks (units) with the XBlocks (HTML content) are rendered as Iframes. The edit link is rendered as a part of the Iframe for this PoC.

2022-06-24 14:30 UTC, navinkarkera commented
@tecoholic We should probably get two edit links or open both the files in online ide for cases of a single section divided into two files like below. What do you think?

![image](https://user-images.githubusercontent.com/10894099/175555929-cc052e47-f40c-4bec-bbf7-bf894958bcdf.png)


This chapter corresponds to two files in the repo:

![image](https://user-images.githubusercontent.com/10894099/175555577-84a294dd-71e1-4c9f-9641-6e46fafa6c16.png)

![image](https://user-images.githubusercontent.com/10894099/175555524-c9ba2419-4cd5-40bd-8af3-9801960043c9.png)

2022-06-24 14:30 UTC, navinkarkera requested changes

2022-06-24 14:30 UTC, navinkarkera commented on edit_links/pipeline.py
> +            config = EditLinkedCourse.objects.get(course_id=course_id)
@tecoholic `get` raises an exception if the `course_id` is not added to the model.

![image](https://user-images.githubusercontent.com/10894099/175554823-b5f4bf42-a60a-4f9f-84f9-3afa6107a013.png)

2022-06-27 11:16 UTC, tecoholic commented on edit_links/pipeline.py
> +            config = EditLinkedCourse.objects.get(course_id=course_id)
@navinkarkera  Great catch. I will move this to a more defensive query like `filter().first()` so we can just skip over if there are no configs.

2022-06-27 11:42 UTC, tecoholic commented
> @tecoholic We should probably get two edit links or open both the files in online ide for cases of a single section divided into two files like below. What do you think?
> 

@navinkarkera I am not really sure how to handle this situation. 

From the UX point of view I see the following issues:
1. Opening multiple tabs - as in 1 tab per file would be a poor UX as the web IDEs provide a single window to edit multiple files.
2. I tried researching the Gitlab URL pattern for opening multiple files in the Gitlab IDE, there doesn't seem to be one. However, the IDE does open multiple files when opening a PR using the PR Link. But, doesn't have a way to pass multiple files through a single URL. Also I haven't tested this in Github Editor yet, not sure what the support for multiple files are there.

Since this is a PoC, I am thinking opening the first file should be sufficient. Multiple file support can be added later.

2022-07-24 14:50 UTC, tecoholic commented
@navinkarkera I have updated the PR with new changes, including re-implementing the filter following the guidelines from [this issue description](https://gitlab.com/mooc-floss/mooc-floss/-/issues/121) relating to configuration, readme documentation and translations. Kindly review when you have the time.

2022-07-25 07:51 UTC, navinkarkera commented
@tecoholic  LGTM :+1:, we just need to make sure that the tests pass. (Adding `_clear_dirty_fields` to mock `HtmlBlockWithMixins` should work). 

Just one question, Where can I find the source code for `HtmlBlockWithMixins`?

- [x] I tested this: (describe what you tested)
- [x] I read through the code
- [x] I checked for accessibility issues
- [x] Includes documentation
- [ ] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.

2022-07-25 09:35 UTC, tecoholic commented
@navinkarkera Thanks fore reviewing this.

> @tecoholic LGTM +1, we just need to make sure that the tests pass. (Adding `_clear_dirty_fields` to mock `HtmlBlockWithMixins` should work).

Good catch. I will implement it. 

> Just one question, Where can I find the source code for `HtmlBlockWithMixins`?
> 

It is custom class created by the XBlock Runtime [using the Mixologist](https://github.com/openedx/XBlock/blob/master/xblock/runtime.py#L1310). It takes the [HTMLXBlock](https://github.com/openedx/edx-platform/blob/master/xmodule/html_module.py#L378) and resolves the extra mixins and generates a new class with the name "HTMLBlock" + "WithMixins".

2022-07-25 10:06 UTC, tecoholic commented
The PR will be merged once the dependencies on openedx-filters are merged and its version is set in the requirements.

2022-08-04 22:30 UTC, bradenmacdonald commented on README.rst
> +        }
If you want, you could also make it so users can configure this per-course in Studio.

If you enable [`ENABLE_OTHER_COURSE_SETTINGS `](https://github.com/openedx/edx-platform/blob/3d967001898279edd290c8e509206980e5506124/cms/envs/common.py#L253-L255), the Studio Advanced Settings page will show "[Other Course Settings](https://github.com/openedx/edx-platform/blob/e73139d60f43fd2f4b455b88ddf0394cffeb4e3a/xmodule/course_module.py#L1021-L1030)", and you could put the URL in there like `{ "git_repo": "https://gitlab.com/awesome-course/-/tree/master/course/" }`

No need to change anything for now, but if people want an easier way to configure this in the future, that's what I'd recommend.

2022-08-04 23:27 UTC, bradenmacdonald commented on edit_links/pipeline.py
> +
Should this show the closing `}` as well, to match the `"OPEN_EDX_FILTERS_CONFIG": {` line?

2022-08-04 23:31 UTC, bradenmacdonald commented on edit_links/pipeline.py
> +            # the dirty fields.
Instead of modifying the `data` field, why don't you just wrap the [`get_html()`](https://github.com/openedx/edx-platform/blob/e73139d60f43fd2f4b455b88ddf0394cffeb4e3a/xmodule/html_module.py#L118-L127) method? That would be more clear and then you also don't have to use this protected method.

2022-08-11 10:14 UTC, tecoholic commented on edit_links/pipeline.py
> +            # the dirty fields.
@bradenmacdonald That was a wonderful idea. Thank you. I have implemented a wrapper for `get_html` and it works as expected without any hacky function calls.

2022-08-15 20:16 UTC, bradenmacdonald commented on edit_links/pipeline.py
> +            # the dirty fields.
Glad to hear that. Is this ready for final review?

2022-08-25 23:47 UTC, merged